sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: SyCBucVLrWRnCS2W+NbtDYfq6Kgg4t0xUnXtv/WWkFcpta8Qonn+9RFrJJ1YcYkKKpg/x/784ZNaw2wohHqB1cyqgZheyGvomlEnLqYF7FPwwhbMsfZkRMgFO9vzRNsF9KZIjDW9k7zn0vPEg2zinOa/YmOKn7w7ZsRoj1Sm60kwqnNRtFi+1QE+p1H/+lOSlTp9pb9l9bbtWX6N903OLpzGtycnL4F7A0Ek3icIufrkLcokmEJV0S3+VdbtcLYQiidocroCCSVz5ViBUcG2rolHRe9sTeKTC1kEl5JDxriAn/D8wbxZ3HcvBtcG958yT0YQnEIlMxHerd9K/qM2Wh0bMEVrYmDvbsjFaVut+obDxauT3WpH+Llaeaarjn3GuD4tjKJ99tF6Gl2QDufBN5+/pMk1v84fYdFafgQZKIgwz7ZRRdcLJIxcveIe72QK6OhbPtxmqQIcv+eTbUYspsZ8iNwDiydnpWlmGndIAc04LW5DMogAMBBjsMEcpgofZvjichHPTilPXvSTKPWGjzdldfZpcEs9lf10j7jTYaV2tVoZnJDfMzsPfDRXP3AEs5VTFVmT+iUs1zCltxCawT6dnEZyTUrS2x6hU/TYnzJJ1FWruylWidKFnLYsR2jen/pJAGEWqTaV14vVJ8fZ3LloC3ebFtMqUeFP+gDioag=
  - secure: mi4zt77q9zKWBqqlBPNgmyBJUoeaqG7F39s7gvA2Jqp023gO1Gg0tB5JNK32Gy7ADNryetW8FoeQzN51CHIGTV4JWPtpiaHQEpOKZloDuW/1Xge6Yz/N0N9jF1/4KmGTIqIx5MmKMec1gGPeBM+OzEeofPvNc1qXe+899bWzjIVF7wUTnFcetKjZcjgOmWnduWbLveGxmmGvJc8oWrcQNYegaR4j/6+1Ziay8L58nKZcxrzaZ/sMtIizlt+ehhpdypgEuLcUO5445vblD6bneS4kckLreTB2XQVOX+TyniJ8lwC62/LA99+by37FMXLgqkBIUMElvQP3bKm18IkCZmYALhqzYB613fzPwGVRvzBHcsuZ1RBmDheLt7NTrWxPSFhARAHe5px26Sb67+MC7heOgPYMaK+o5HGh5RNhrOJzwM72EElNA5D28azME5PnfgIJt+4VU8idc3j/7FmeArcNQwH/qDzkJCZaLfG7Qr4g2doasamUXqgixkEeaHh59jJHN7LL4UTQt+1UNNIFxXa/tIvvd4Cq6ZtRIrMFkG8ODx88jkfs9K3vTorZrawH6J5++hXjVzMmwwF40AWVlPeeoZ/YHj9ngaZI+XrHDuLFFcCc4Yx5gy7I6AA8xBxQ0Gu8wpJNki2VVItUnSPua+b8N2ZsT8ub/4pNb447e0Q=
  - secure: OdDpQLciosahEMQYrXWFUOBq8MBMNhUAvA7NznjYyM8ZwkJopqxX5wOwEO7B6zssMRzBUkR0HOKptp4pEZ2IsY6S9JMrJJB/CJNUS+Y09plb+ZIGVecBKPZCnEhEHPwgCsYOkD9Oq+ipSFSFGHXfkbqxIld8hlatCab1Msf+MEDlL5po3PkC0ucnABoaU92g/VZMm+KWRWCrD6McTrJ2ZndwEw7SEe3L7ni0Ah7XwMgXcD+2AWB1/W7TCpBOYg5coOIWJvvGB7V1ZWchknFZTbvwyCPG/rnO5M4xtYTVJLTKTxe4yDY5kJLAOgDOpUWUe0vNgogvh0RIBH6vgxF6vnrn1oe+a15ftQI4ffzpz97dBHnrO+vjK+cp0sxn5cHCdvnL/FMedXV4+oCxe6x1yxxUNxygiAqG7LCaWKz4tyN+j2wKP0doGC/1suWKoY2f/ylo2uzJffkIWCvZ7Tb+Nke8ZpFIYD+rR1+dhqpkO+hbWvBPwIivl9hJY7ufJJ+2t4bpuopFhExQJygVWRI4PEaReYsvT+547dx5sgADQ3aE49FyUZ0RMPLnx2Zdc+0I0wf3PT+mj+AowrlaC8bPhm/lEc3wjb2YZ3J+TPYtlCb+6n0LrdcESGHojJglOlkERa4LpaLMTtzatRtwlmwv/cXF0IV3IbZ3h1t8hG4kR24=
